# Generated by Django 6.0.6 on 2026-06-11 03:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='galeriaitem',
            options={'ordering': ['-creado']},
        ),
        migrations.AlterModelOptions(
            name='resena',
            options={'ordering': ['-creado']},
        ),
        migrations.AlterModelOptions(
            name='solicitud',
            options={'ordering': ['-creado']},
        ),
        migrations.AlterModelOptions(
            name='trabajo',
            options={'ordering': ['-creado']},
        ),
        migrations.AddField(
            model_name='solicitud',
            name='mensaje',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='rapida',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='trabajo',
            name='actualizado',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='trabajo',
            name='beneficios',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='trabajo',
            name='estado_vacante',
            field=models.CharField(choices=[('disponible', 'Disponible'), ('en_proceso', 'En proceso'), ('ocupada', 'Ocupada')], default='disponible', max_length=20),
        ),
        migrations.AddField(
            model_name='trabajo',
            name='lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trabajo',
            name='lng',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trabajo',
            name='requisitos',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='trabajo',
            name='vistas',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='fotos/'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='lng',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='notif_email',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='notif_sistema',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='trabajo',
            name='categoria',
            field=models.CharField(choices=[('electricidad', 'Electricidad'), ('plomeria', 'Plomería'), ('carpinteria', 'Carpintería'), ('pintura', 'Pintura'), ('limpieza', 'Limpieza'), ('jardineria', 'Jardinería'), ('reparaciones', 'Reparaciones'), ('instalaciones', 'Instalaciones'), ('albanileria', 'Albañilería'), ('soldadura', 'Soldadura'), ('mecanica', 'Mecánica'), ('informatica', 'Informática'), ('otro', 'Otro')], max_length=50),
        ),
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('solicitud', 'Nueva solicitud'), ('estado', 'Cambio de estado'), ('contratado', 'Contratado'), ('resena', 'Nueva reseña'), ('sistema', 'Sistema')], default='sistema', max_length=20)),
                ('titulo', models.CharField(max_length=200)),
                ('mensaje', models.TextField()),
                ('leida', models.BooleanField(default=False)),
                ('url', models.CharField(blank=True, max_length=300)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-creado'],
            },
        ),
        migrations.CreateModel(
            name='PasswordResetToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=100, unique=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('usado', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
