# Generated by Django 6.1 on 2026-08-14 18:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_galeriaitem_options_alter_resena_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='trabajo',
            name='duracion',
            field=models.CharField(blank=True, help_text='Ej: 3 días, 1 semana', max_length=100),
        ),
        migrations.AddField(
            model_name='trabajo',
            name='modalidad',
            field=models.CharField(choices=[('presencial', 'Presencial'), ('remoto', 'Remoto'), ('hibrido', 'Híbrido')], default='presencial', max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='disponible',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='experiencia_anos',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='portfolio_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='tarifa_hora',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='notificacion',
            name='tipo',
            field=models.CharField(choices=[('solicitud', 'Nueva solicitud'), ('estado', 'Cambio de estado'), ('contratado', 'Contratado'), ('resena', 'Nueva reseña'), ('sistema', 'Sistema'), ('match', 'Nuevo match')], default='sistema', max_length=20),
        ),
        migrations.AlterField(
            model_name='trabajo',
            name='categoria',
            field=models.CharField(choices=[('electricidad', 'Electricidad'), ('plomeria', 'Plomería'), ('carpinteria', 'Carpintería'), ('pintura', 'Pintura'), ('limpieza', 'Limpieza'), ('jardineria', 'Jardinería'), ('reparaciones', 'Reparaciones'), ('instalaciones', 'Instalaciones'), ('albanileria', 'Albañilería'), ('soldadura', 'Soldadura'), ('mecanica', 'Mecánica'), ('informatica', 'Informática'), ('diseno', 'Diseño'), ('acabados', 'Acabados'), ('otro', 'Otro')], max_length=50),
        ),
        migrations.CreateModel(
            name='Mensaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
                ('leido', models.BooleanField(default=False)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensajes_enviados', to=settings.AUTH_USER_MODEL)),
                ('solicitud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensajes', to='core.solicitud')),
            ],
            options={
                'ordering': ['creado'],
            },
        ),
    ]
