# Generated by Django 5.2.7 on 2026-08-24 22:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_logro_solicitud_tarifa_propuesta_trabajo_fecha_pago_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='galeriaitem',
            name='descripcion',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='resena',
            name='etiquetas',
            field=models.CharField(blank=True, help_text='Etiquetas separadas por comas', max_length=255),
        ),
        migrations.AddField(
            model_name='resena',
            name='solicitud',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resenas', to='core.solicitud'),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('en_revision', 'En revisión'), ('aceptado', 'Aceptado'), ('rechazado', 'Rechazado'), ('contratado', 'Contratado'), ('en_progreso', 'En progreso'), ('completado', 'Completado')], default='pendiente', max_length=20),
        ),
    ]
