# Generated by Django 5.2.7 on 2026-08-24 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_galeriaitem_descripcion_resena_etiquetas_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensaje',
            name='adjunto',
            field=models.FileField(blank=True, null=True, upload_to='chat_adjuntos/'),
        ),
        migrations.AddField(
            model_name='mensaje',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to='chat_audios/'),
        ),
        migrations.AddField(
            model_name='mensaje',
            name='estado_entrega',
            field=models.CharField(choices=[('enviado', 'Enviado'), ('entregado', 'Entregado'), ('leido', 'Leído')], default='enviado', max_length=20),
        ),
        migrations.AddField(
            model_name='mensaje',
            name='lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mensaje',
            name='lng',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mensaje',
            name='ubicacion_nombre',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='trabajo',
            name='comision_plataforma',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
        migrations.AddField(
            model_name='trabajo',
            name='contacto_emergencia_sitio',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='trabajo',
            name='fecha_inicio',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trabajo',
            name='fecha_limite',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='trabajo',
            name='herramientas',
            field=models.CharField(choices=[('empleador', 'Proporcionadas por el empleador'), ('trabajador', 'El trabajador debe traer sus herramientas'), ('ambos', 'Mixto')], default='empleador', max_length=30),
        ),
        migrations.AddField(
            model_name='trabajo',
            name='horario',
            field=models.CharField(blank=True, help_text='Ej: 8:00 AM - 5:00 PM', max_length=100),
        ),
        migrations.AddField(
            model_name='trabajo',
            name='metodo_pago_id',
            field=models.CharField(blank=True, help_text='ID de transacción / comprobante de tarjeta', max_length=100),
        ),
        migrations.AddField(
            model_name='trabajo',
            name='nivel_experiencia',
            field=models.CharField(choices=[('sin_experiencia', 'Sin experiencia previa'), ('intermedio', 'Intermedio (1-3 años)'), ('experto', 'Experto (+3 años)')], default='intermedio', max_length=30),
        ),
        migrations.AddField(
            model_name='trabajo',
            name='tarifa_urgencia',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8),
        ),
        migrations.AddField(
            model_name='trabajo',
            name='total_a_pagar',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='trabajo',
            name='transporte_propio',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='trabajo',
            name='vacantes_disponibles',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='anos_operacion',
            field=models.PositiveIntegerField(default=0, help_text='Años de operar en el mercado'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='certificaciones',
            field=models.TextField(blank=True, help_text='Cursos, diplomas o licencias técnicas'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='contacto_cargo',
            field=models.CharField(blank=True, help_text='Cargo o departamento de contacto', max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='contacto_emergencia',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='disponibilidad_horario',
            field=models.CharField(blank=True, help_text='Ej: Lunes a Viernes, Fines de semana, Turno completo', max_length=100),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='dui',
            field=models.CharField(blank=True, help_text='Documento Único de Identidad', max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='giro_comercial',
            field=models.CharField(blank=True, help_text='Giro o actividad económica', max_length=150),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='nit_nrc',
            field=models.CharField(blank=True, help_text='NIT o NRC fiscal', max_length=30),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='nivel_educativo',
            field=models.CharField(blank=True, choices=[('basica', 'Educación Básica'), ('media', 'Bachillerato / Secundaria'), ('tecnico', 'Técnico Vocacional'), ('universitario', 'Universitario / Superior')], default='media', max_length=50),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='redes_sociales',
            field=models.CharField(blank=True, help_text='LinkedIn / Instagram / Facebook', max_length=255),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='sitio_web',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='vehiculo',
            field=models.CharField(choices=[('ninguno', 'Ninguno / Transporte público'), ('moto', 'Motocicleta'), ('carro', 'Automóvil'), ('camioneta', 'Camioneta / Pick-up')], default='ninguno', max_length=30),
        ),
        migrations.AlterField(
            model_name='mensaje',
            name='texto',
            field=models.TextField(blank=True),
        ),
    ]
