# Generated by Django 5.2.7 on 2026-08-25 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_mensaje_adjunto_mensaje_audio_mensaje_estado_entrega_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitud',
            name='metodo_pago_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='pagado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='total_a_pagar',
            field=models.DecimalField(decimal_places=2, default=1.5, max_digits=10),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='cantidad_empleados',
            field=models.CharField(blank=True, choices=[('1-10', '1 a 10 empleados'), ('11-50', '11 a 50 empleados'), ('51-200', '51 a 200 empleados'), ('200+', 'Más de 200 empleados')], default='1-10', max_length=50),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='expectativa_salarial',
            field=models.CharField(blank=True, help_text='Ej: $400 - $600 mensual', max_length=50),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='idiomas',
            field=models.CharField(blank=True, help_text='Ej: Inglés (Básico), Español (Nativo)', max_length=150),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='referencias_personales',
            field=models.TextField(blank=True, help_text='Nombres y teléfonos de referencias'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='registro_fiscal',
            field=models.FileField(blank=True, help_text='Sube una copia del registro de la empresa', null=True, upload_to='documentos_fiscales/'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='tipo_empresa',
            field=models.CharField(blank=True, choices=[('privada', 'Empresa Privada'), ('publica', 'Institución Pública'), ('ong', 'ONG / Sin fines de lucro'), ('independiente', 'Profesional Independiente')], default='privada', max_length=50),
        ),
    ]
