# Generated by Django 5.2.7 on 2026-08-26 04:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_emailverificationtoken'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EvidenciaTrabajo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('contratista', 'Contratista'), ('trabajador', 'Trabajador')], max_length=20)),
                ('imagen', models.ImageField(upload_to='evidencias/')),
                ('descripcion', models.TextField(blank=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('solicitud', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidencias', to='core.solicitud')),
                ('subido_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['creado'],
            },
        ),
        migrations.CreateModel(
            name='TransaccionEscrow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estado', models.CharField(choices=[('retenido', 'Retenido en Escrow'), ('liberado', 'Liberado al Trabajador'), ('reembolsado', 'Reembolsado al Contratista'), ('en_disputa', 'En Disputa')], default='retenido', max_length=20)),
                ('metodo_pago_simulado', models.CharField(blank=True, max_length=100)),
                ('comprobante_pdf', models.FileField(blank=True, null=True, upload_to='comprobantes/')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('solicitud', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='escrow', to='core.solicitud')),
            ],
            options={
                'ordering': ['-creado'],
            },
        ),
    ]
