# Generated by Django 5.2.7 on 2026-08-26 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_evidenciatrabajo_transaccionescrow'),
    ]

    operations = [
        migrations.RenameField(
            model_name='galeriaitem',
            old_name='trabajador',
            new_name='usuario',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='cv_pdf',
            field=models.FileField(blank=True, help_text='Curriculum Vitae (PDF u otro doc)', null=True, upload_to='cvs/'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='certificaciones',
            field=models.TextField(blank=True, help_text='Postgrados, certificaciones o cursos realizados'),
        ),
    ]
