# Generated by Django 5.2.7 on 2026-08-26 05:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_rename_trabajador_galeriaitem_usuario_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContratoDigital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alcance_trabajo', models.TextField()),
                ('plazo_entrega', models.DateField()),
                ('costo_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('firma_contratista', models.CharField(blank=True, max_length=150)),
                ('firmado_contratista_at', models.DateTimeField(blank=True, null=True)),
                ('firma_trabajador', models.CharField(blank=True, max_length=150)),
                ('firmado_trabajador_at', models.DateTimeField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente de Firma'), ('vigente', 'Vigente / Firmado'), ('completado', 'Finalizado')], default='pendiente', max_length=20)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('solicitud', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contrato', to='core.solicitud')),
            ],
        ),
    ]
