# Generated by Django 5.2.7 on 2026-08-26 05:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_contratodigital'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Disputa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.TextField()),
                ('evidencia_imagen', models.ImageField(blank=True, null=True, upload_to='disputas/')),
                ('estado', models.CharField(choices=[('abierta', 'Abierta / En Mediación'), ('en_revision', 'En Revisión por Soporte'), ('resuelta_reembolso', 'Resuelta (Reembolsado al Cliente)'), ('resuelta_pago', 'Resuelta (Liberado al Trabajador)')], default='abierta', max_length=30)),
                ('resolucion_comentario', models.TextField(blank=True, help_text='Comentario del mediador de Chambazo')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disputas_creadas', to=settings.AUTH_USER_MODEL)),
                ('solicitud', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='disputa', to='core.solicitud')),
            ],
            options={
                'ordering': ['-creado'],
            },
        ),
    ]
