# Generated by Django 5.2.7 on 2026-08-26 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_disputa'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='comentario_verificacion',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='doc_frontal',
            field=models.ImageField(blank=True, null=True, upload_to='verificaciones/'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='doc_reverso',
            field=models.ImageField(blank=True, null=True, upload_to='verificaciones/'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='selfie',
            field=models.ImageField(blank=True, null=True, upload_to='verificaciones/'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='verificacion_estado',
            field=models.CharField(choices=[('no_iniciado', 'No Iniciado'), ('pendiente', 'En Revisión'), ('aprobado', 'Verificado'), ('rechazado', 'Rechazado')], default='no_iniciado', max_length=20),
        ),
    ]
