# Generated by Django 6.1.1 on 2026-09-25 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_userprofile_comentario_verificacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='ubicacion',
            field=models.CharField(blank=True, max_length=180),
        ),
    ]
