# Generated by Django 6.1.1 on 2026-09-26 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_userprofile_ubicacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='nivel_educativo',
            field=models.CharField(blank=True, choices=[('primaria', 'Educación Primaria (1° a 6° grado)'), ('basica', 'Educación Básica / Tercer Ciclo (7° a 9° grado)'), ('media', 'Bachillerato / Educación Media'), ('tecnico', 'Técnico Vocacional'), ('universitario_curso', 'Universitario (en curso)'), ('universitario', 'Universitario Graduado'), ('postgrado', 'Postgrado / Maestría')], default='media', max_length=50),
        ),
    ]
