# Generated by Django 6.1.1 on 2026-09-27 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_userprofile_nivel_educativo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='contacto_emergencia',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='expectativa_salarial',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='experiencia_anos',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='tarifa_hora',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='disponibilidad_horario',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='disponibilidad_horario',
            field=models.JSONField(blank=True, default=dict, help_text='{"dias": ["lun","mar",...], "franja": "manana|tarde|noche|completo"}'),
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='idiomas',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='idiomas',
            field=models.JSONField(blank=True, default=list, help_text='[{"nombre": "Inglés", "nivel": "Básico"}, ...]'),
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='referencias_personales',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='referencias_personales',
            field=models.JSONField(blank=True, default=list, help_text='[{"nombre": "...", "telefono": "..."}, ...]'),
        ),
    ]
