# Generated by Django 6.1.1 on 2026-09-27 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_remove_userprofile_contacto_emergencia_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='rol',
            field=models.CharField(choices=[('trabajador', 'Trabajador'), ('contratista', 'Contratista'), ('administrador', 'Administrador')], max_length=20),
        ),
    ]
