# Generated by Django 5.2.7 on 2026-10-07 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_reporteusuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='resena',
            name='motivo_reporte',
            field=models.TextField(blank=True, help_text='Motivo del reporte'),
        ),
        migrations.AddField(
            model_name='resena',
            name='reportada',
            field=models.BooleanField(default=False, help_text='Indica si la reseña fue reportada por inapropiada'),
        ),
        migrations.AddField(
            model_name='solicitud',
            name='motivo_descarte',
            field=models.CharField(blank=True, help_text='Motivo por el cual fue descartado', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='trabajo',
            name='tipo_oportunidad',
            field=models.CharField(choices=[('informal', 'Chamba Rápida / Ocasional'), ('formal', 'Empleo Formal (Contrato / Empresa)')], default='informal', help_text='Diferenciación entre trabajo formal e informal', max_length=20),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='notif_mensajes',
            field=models.BooleanField(default=True, help_text='Notificación de nuevos mensajes'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='notif_recordatorios',
            field=models.BooleanField(default=True, help_text='Recordatorios de citas/entrevistas'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='onboarding_completado',
            field=models.BooleanField(default=False, help_text='Guía inicial completada'),
        ),
    ]
